name = "PlutoHTML"
uuid = "359b1769-a58e-495b-9770-312e911026ad"
authors = ["Rik Huijzer <rikhuijzer@pm.me>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
Pluto = "0.16"
